name: Deploy Web Demo to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'lib/**'
      - 'assets/**'
      - 'pubspec.yaml'
      - '.github/workflows/flutter-web-ghpages.yml'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions: { contents: write, pages: write, id-token: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.22.2' }
      - name: Pub get
        run: flutter pub get
      - name: Build Flutter Web
        run: flutter build web --release --web-renderer canvaskit --base-href "/Calmaexpress/"
      - name: Add 404.html for SPA routing
        run: cp build/web/index.html build/web/404.html
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
